Error: "num" was being called from conf.py, but it did not exist.
fix: call "num2" .
Explanation: Proper calling of variable is needed. 